version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  user-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: user-service-db
    volumes:
      - user_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  order-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: order-service-db
      PGPORT: 5433
    volumes:
      - order_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5433"

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: user-db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: 1234
      DB_NAME: user-service-db
      DB_SSL_MODE: disable
      JWT_SECRET: your_jwt_secret
    ports:
      - "8080:8080"
    depends_on:
      - user-db
    entrypoint: ["./wait-for-it.sh", "user-db:5432", "--", "./main"]

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: order-db
      DB_PORT: 5433
      DB_USER: user
      DB_PASSWORD: 1234
      DB_NAME: order-service-db
      DB_SSL_MODE: disable
      JWT_SECRET: your_jwt_secret
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8081:8081"
    depends_on:
      - order-db
      - rabbitmq
    entrypoint: ["./wait-for-it.sh", "order-db:5433", "--", "./wait-for-it.sh", "rabbitmq:5672", "--", "./main"]

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: payment-db
      DB_PORT: 5434
      DB_USER: user
      DB_PASSWORD: 1234
      DB_NAME: payment-service-db
      DB_SSL_MODE: disable
      JWT_SECRET: your_jwt_secret
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8082:8082"
    depends_on:
      - payment-db
      - rabbitmq
    entrypoint: ["./wait-for-it.sh", "payment-db:5434", "--", "./wait-for-it.sh", "rabbitmq:5672", "--", "./main"]

  payment-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: payment-service-db
      PGPORT: 5434
    volumes:
      - payment_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5434"

volumes:
  user_db_data:
  order_db_data:
  payment_db_data:


