CREATE TABLE payments (
    id SERIAL PRIMARY KEY,
    orderID INTEGER NOT NULL,
    userID INTEGER NOT NULL,
    amount INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
